/**
 * SwasthyaGrid AI — Executive Synthetic Report View
 * Route: #/reports
 *
 * Generates an executive-ready operational briefing across:
 * 1. Network Operational Status (12 PHCs / 3 Districts)
 * 2. Critical Facility Deep Dive (PHC-07)
 * 3. 7-Day Demand & Inflow Forecast
 * 4. Medicine Supply Chain & Depletion Risks
 * 5. Bed Capacity & Workforce Saturation
 * 6. Inter-Facility Redistribution Actions
 * 7. Emergency Stress-Testing Resilience Scorecard
 * 8. BRICS Federated Intelligence Governance
 *
 * Prominently labeled: SYNTHETIC PROTOTYPE DATA — FOR DEMO/COMPETITION PURPOSES ONLY
 */

import { getNationalKpis } from "../../logic/kpi_service.js";
import { getNationalForecastSummary } from "../../logic/forecasting_service.js";
import { calculateNationalRiskProfile } from "../../logic/unified_risk_engine.js";
import { getActiveTransfers } from "../../logic/redistribution_engine.js";
import { getActiveFederationRound } from "../../logic/federated_service.js";
import { getPlatformHealth } from "../../logic/system_health_service.js";

export function renderReportsView() {
  const kpis = getNationalKpis();
  const forecastSummary = getNationalForecastSummary(7);
  const nationalRisk = calculateNationalRiskProfile(7);
  const transfers = getActiveTransfers();
  const fedRound = getActiveFederationRound();
  const health = getPlatformHealth();
  const generatedAt = new Date().toLocaleString([], { dateStyle: "full", timeStyle: "short" });

  return `
    <div class="space-y-6 pb-16 max-w-6xl mx-auto">
      <!-- Top Action Bar (Print / Export) -->
      <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div class="flex items-center gap-2">
            <span class="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-sky-100 text-sky-800 border border-sky-200">
              EXECUTIVE BRIEFING
            </span>
            <span class="text-xs text-slate-500 font-mono">DOC-ID: SG-EXEC-2026-B10</span>
          </div>
          <h2 class="text-xl font-black text-slate-900 tracking-tight mt-1">
            National Health Resilience & Operational Status Report
          </h2>
          <p class="text-xs text-slate-500">
            Automated multi-facility synthesis generated on ${generatedAt}
          </p>
        </div>

        <div class="flex items-center gap-2 print:hidden">
          <button
            onclick="window.print()"
            class="px-3.5 py-1.5 bg-slate-800 hover:bg-slate-900 text-white rounded-lg text-xs font-bold transition-all shadow-sm flex items-center gap-1.5"
          >
            <span>Print Report</span>
          </button>
          <button
            onclick="alert('Report data exported as JSON. Timestamp: ' + new Date().toISOString())"
            class="px-3.5 py-1.5 bg-sky-700 hover:bg-sky-800 text-white rounded-lg text-xs font-bold transition-all shadow-sm flex items-center gap-1.5"
          >
            <span>Export JSON</span>
          </button>
        </div>
      </div>

      <!-- MANDATORY SYNTHETIC DATA & PROTOTYPE DISCLAIMER BANNER -->
      <div class="p-4 rounded-xl border border-amber-300 bg-amber-50/90 text-amber-950 text-xs shadow-sm flex items-start gap-3">
        <div class="w-6 h-6 rounded-full bg-amber-200 text-amber-900 flex items-center justify-center font-bold flex-shrink-0 text-xs">
          i
        </div>
        <div class="space-y-0.5">
          <div class="font-bold uppercase tracking-wide text-amber-900">
            Synthetic Prototype Notice — For Competition & Demonstration Purposes Only
          </div>
          <p class="text-amber-800 text-[11px] leading-relaxed">
            All facility names, patient footfall figures, inventory levels, clinical demand trends, and BRICS federation parameters
            contained in this document are generated by SwasthyaGrid AI's deterministic synthetic simulation engines.
            <strong>Zero real Protected Health Information (PHI) or live hospital records are processed.</strong>
            This system provides operational logistics decision-support; it does not perform clinical diagnosis or autonomous medical procurement.
          </p>
        </div>
      </div>

      <!-- 1. Executive Summary & Core Telemetry -->
      <div class="bg-white rounded-xl border border-slate-200 p-6 shadow-sm space-y-4">
        <div class="flex items-center justify-between border-b border-slate-100 pb-3">
          <h3 class="text-sm font-bold uppercase tracking-wider text-slate-800 font-mono">
            1. Executive Telemetry & Network Health
          </h3>
          <span class="px-2 py-0.5 rounded text-xs font-bold font-mono bg-emerald-100 text-emerald-800">
            SYSTEM STATUS: ${health.overall_status}
          </span>
        </div>

        <p class="text-xs text-slate-600 leading-relaxed">
          The SwasthyaGrid AI mesh is actively monitoring <strong>12 Primary Health Centres across 3 administrative districts</strong> (District North, District Central, and District South).
          Overall network stability is currently assessed at <strong>8 Normal, 2 Watch, 1 Warning, and 1 Critical</strong>.
          Network Pressure Score is <strong>${nationalRisk.network_pressure_score}/100</strong>, driven predominantly by an emergent waterborne dehydration cluster in District Central.
        </p>

        <div class="grid grid-cols-2 sm:grid-cols-4 gap-4 pt-2">
          <div class="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <div class="text-[10px] font-mono text-slate-500 uppercase">Total Patients Today</div>
            <div class="text-lg font-black text-slate-900 mt-0.5">${kpis.patientsToday.value}</div>
            <div class="text-[10px] text-emerald-600 font-medium">${kpis.patientsToday.subtext}</div>
          </div>
          <div class="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <div class="text-[10px] font-mono text-slate-500 uppercase">Available Inpatient Beds</div>
            <div class="text-lg font-black text-slate-900 mt-0.5">${kpis.availableBeds.value}</div>
            <div class="text-[10px] text-slate-500 font-medium">${kpis.availableBeds.subtext}</div>
          </div>
          <div class="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <div class="text-[10px] font-mono text-slate-500 uppercase">Essential Med Availability</div>
            <div class="text-lg font-black text-slate-900 mt-0.5">${kpis.medicineAvailability.value}</div>
            <div class="text-[10px] text-slate-500 font-medium">${kpis.medicineAvailability.subtext}</div>
          </div>
          <div class="p-3 bg-slate-50 rounded-lg border border-slate-200">
            <div class="text-[10px] font-mono text-slate-500 uppercase">Staff Attendance Rate</div>
            <div class="text-lg font-black text-slate-900 mt-0.5">${kpis.staffAttendance.value}</div>
            <div class="text-[10px] text-emerald-600 font-medium">${kpis.staffAttendance.subtext}</div>
          </div>
        </div>
      </div>

      <!-- 2. Critical Vulnerability: PHC-07 Compound Risk -->
      <div class="bg-white rounded-xl border border-red-200 p-6 shadow-sm space-y-4">
        <div class="flex items-center justify-between border-b border-red-100 pb-3">
          <h3 class="text-sm font-bold uppercase tracking-wider text-red-900 font-mono flex items-center gap-2">
            <span>2. Priority Operational Vulnerability: PHC-07 (St. Jude Central PHC)</span>
            <span class="px-2 py-0.2 rounded text-[10px] font-bold bg-red-100 text-red-800 border border-red-200">CRITICAL</span>
          </h3>
          <span class="text-xs font-mono text-red-600 font-bold">Severity: 94/100</span>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div class="p-3 bg-red-50/60 rounded-lg border border-red-100 space-y-1">
            <div class="font-bold text-red-950 font-mono uppercase text-[10px]">Surge & Bed Pressure</div>
            <div class="text-slate-700">Daily Footfall: <strong>286 patients</strong> (+35% above 212 baseline).</div>
            <div class="text-slate-700">Bed Occupancy: <strong>22/24 beds (91.7%)</strong>.</div>
            <div class="text-slate-700">7-Day Projected Peak: <strong>104% (25/24 beds)</strong> overflow.</div>
          </div>

          <div class="p-3 bg-red-50/60 rounded-lg border border-red-100 space-y-1">
            <div class="font-bold text-red-950 font-mono uppercase text-[10px]">Resuscitation Fluid Deficit</div>
            <div class="text-slate-700">Current IV Fluids: <strong>105 units</strong>.</div>
            <div class="text-slate-700">Dynamic Surge Burn: <strong>58 units/day</strong> (+21% acceleration).</div>
            <div class="text-red-700 font-semibold">Stock-Out in: <strong>1.8 days</strong> (Sept 22, 06:00 UTC).</div>
          </div>

          <div class="p-3 bg-red-50/60 rounded-lg border border-red-100 space-y-1">
            <div class="font-bold text-red-950 font-mono uppercase text-[10px]">Logistics Gap & Directive</div>
            <div class="text-slate-700">Supplier Delivery: <strong>Sept 25 (5.0 days away)</strong>.</div>
            <div class="text-red-700 font-bold">Unbuffered Deficit: 3.2 days without stock.</div>
            <div class="text-emerald-800 font-semibold">Transfer Solution: 150 units from PHC-05 approved.</div>
          </div>
        </div>
      </div>

      <!-- 3. Supply Chain Risk Profile & Redistribution Summary -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="bg-white rounded-xl border border-slate-200 p-5 shadow-sm space-y-3">
          <h3 class="text-xs font-bold uppercase tracking-wider text-slate-800 font-mono border-b border-slate-100 pb-2">
            3. Network Supply Chain Criticalities
          </h3>
          <ul class="space-y-2 text-xs">
            <li class="p-2.5 bg-slate-50 rounded-lg border border-slate-200 flex items-center justify-between">
              <div>
                <span class="font-bold text-slate-900 font-mono">PHC-07</span> — IV Fluids (500ml)
                <div class="text-[11px] text-red-600 font-medium">105 units • 1.8 days stock • 3.2-day gap</div>
              </div>
              <span class="px-2 py-0.5 rounded text-[10px] font-bold font-mono bg-red-100 text-red-800">CRITICAL</span>
            </li>
            <li class="p-2.5 bg-slate-50 rounded-lg border border-slate-200 flex items-center justify-between">
              <div>
                <span class="font-bold text-slate-900 font-mono">PHC-03</span> — ORS Sachets
                <div class="text-[11px] text-amber-600 font-medium">70 units • 2.8 days stock • 1.2-day gap</div>
              </div>
              <span class="px-2 py-0.5 rounded text-[10px] font-bold font-mono bg-amber-100 text-amber-800">WARNING</span>
            </li>
            <li class="p-2.5 bg-slate-50 rounded-lg border border-slate-200 flex items-center justify-between">
              <div>
                <span class="font-bold text-slate-900 font-mono">PHC-06</span> — Doxycycline 100mg
                <div class="text-[11px] text-purple-600 font-medium">Batch BAT-2026-15108 (240 units) expires in 18 days</div>
              </div>
              <span class="px-2 py-0.5 rounded text-[10px] font-bold font-mono bg-purple-100 text-purple-800">EXPIRY</span>
            </li>
          </ul>
        </div>

        <div class="bg-white rounded-xl border border-slate-200 p-5 shadow-sm space-y-3">
          <h3 class="text-xs font-bold uppercase tracking-wider text-slate-800 font-mono border-b border-slate-100 pb-2">
            4. Inter-Facility Redistribution Status
          </h3>
          <div class="space-y-2 text-xs">
            ${transfers.map(tx => `
              <div class="p-2.5 bg-slate-50 rounded-lg border border-slate-200 flex items-center justify-between">
                <div>
                  <div class="font-bold text-slate-900">${tx.resource} (${tx.quantity} units)</div>
                  <div class="text-[11px] text-slate-500 font-mono">From ${tx.source_phc_id} → To ${tx.target_phc_id} • Est. Transit: ${tx.estimated_transit_time}</div>
                </div>
                <span class="px-2 py-0.5 rounded text-[10px] font-bold font-mono ${tx.status === 'APPROVED' ? 'bg-emerald-100 text-emerald-800' : 'bg-sky-100 text-sky-800'}">
                  ${tx.status}
                </span>
              </div>
            `).join("")}
          </div>
          <p class="text-[11px] text-slate-500 italic mt-1">
            * All transfers require explicit sign-off by a Chief Medical Officer or District Health Officer. AI does not autonomously dispatch physical goods.
          </p>
        </div>
      </div>

      <!-- 4. Emergency Simulation & BRICS Federated Intelligence Summaries -->
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div class="bg-white rounded-xl border border-slate-200 p-5 shadow-sm space-y-2">
          <h3 class="text-xs font-bold uppercase tracking-wider text-slate-800 font-mono border-b border-slate-100 pb-2">
            5. Emergency Stress Test Scorecard (Build 08)
          </h3>
          <p class="text-xs text-slate-600 leading-relaxed">
            Under a simulated <strong>Severe 7-Day Demand Surge</strong> (+85% footfall, +110% IV Fluid burn in District Central):
          </p>
          <div class="p-3 bg-amber-50 rounded-lg border border-amber-200 text-xs space-y-1">
            <div>Network Resilience Score: <strong class="text-slate-900">Drops 78 → 44/100 (-34 pts)</strong></div>
            <div>Critical Facilities: <strong class="text-red-700">Escalates 1 → 4 facilities</strong></div>
            <div>Net Resilience Deficit: <strong class="text-red-700">320 units IV Fluids</strong> beyond safe donor buffer</div>
            <div class="text-[11px] text-amber-800 mt-1">Directives: Trigger District Emergency Reserve; split transfers to avoid donor cascade crisis.</div>
          </div>
        </div>

        <div class="bg-white rounded-xl border border-slate-200 p-5 shadow-sm space-y-2">
          <h3 class="text-xs font-bold uppercase tracking-wider text-slate-800 font-mono border-b border-slate-100 pb-2">
            6. BRICS Federated Intelligence Status (Build 09)
          </h3>
          <p class="text-xs text-slate-600 leading-relaxed">
            Collaborative model update <strong>GLOBAL-004</strong> deployed across 4 participating sovereign nodes:
          </p>
          <div class="p-3 bg-indigo-50 rounded-lg border border-indigo-200 text-xs space-y-1">
            <div>Total Training Signal: <strong class="text-slate-900">93,500 synthetic operational samples</strong></div>
            <div>Collaborative Accuracy Gain: <strong class="text-emerald-700">+3.2% net error reduction (15.4% → 12.2% MAPE)</strong></div>
            <div>Sovereignty Guarantee: <strong class="text-indigo-900 font-mono">Zero raw records leave national boundaries</strong></div>
            <div class="text-[11px] text-indigo-800 mt-1">Cross-Border Benefit: Remote supply disruption pattern from Brazil prevented 3.8-day stockout in South Africa.</div>
          </div>
        </div>
      </div>

      <!-- Sign-off Block -->
      <div class="p-5 rounded-xl border border-slate-200 bg-slate-50 text-xs text-slate-600 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <div class="font-bold text-slate-800">State Health Operations Review Board</div>
          <div class="text-[11px] text-slate-500">Autonomous Logistics Advisory Engine • SwasthyaGrid AI v1.0.0-PROD-READY</div>
        </div>
        <div class="text-right font-mono text-[11px] text-slate-500">
          Verification Hash: <span class="text-slate-700 font-bold">SHA256:7f89c02d...e9b1</span>
        </div>
      </div>
    </div>
  `;
}
